name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: php-actions/composer@v6
        with:
          php_version: 7.4
          command: ""
      - run: make setup
      - run: make create
      - run: make convert
      - run: make build
      - run: make copy
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
      
